# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScratchmdTest < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc). (TEST RELEASE)"
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.3.44-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.44-test/scratchmd-test_darwin_amd64.tar.gz"
      sha256 "aadf2f2f6285bc010fd3c2ac561426d216e730c21c7739338e2f9fe04fc50ef5"

      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.44-test/scratchmd-test_darwin_arm64.tar.gz"
      sha256 "528ad594ce06fedd4389ada43270d862c0d961cdab1e33dbb07e41d8e642001d"

      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.44-test/scratchmd-test_linux_amd64.tar.gz"
      sha256 "bb55756c1b29ee5657a33b62cf8e51ca32243acca340e9143dab8700b18e33ff"
      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.44-test/scratchmd-test_linux_arm64.tar.gz"
      sha256 "2892d16979e868ce0375b3a5a28cc183b3a3307622f9c472e16847f3aad2a5b3"
      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
  end

  test do
    system "#{bin}/scratchmd-test --version"
  end
end
