# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc). (TEST RELEASE)"
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.2.5-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_darwin_amd64.tar.gz"
      sha256 "b72c17576f25c1cc5d354c8de23d982d2faf7a8a975198b2a6f535fb48e8bbc7"

      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_darwin_arm64.tar.gz"
      sha256 "2158b8bff1cdb8a41712bee53c5a9caa733e9de8ea7af1763abdb0ab24f2f4c3"

      def install
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_linux_amd64.tar.gz"
      sha256 "29682ccb74202a7627381073e6c05dbdaa494e98b2c52bb25c51926a43b268d6"
      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_linux_arm64.tar.gz"
      sha256 "0027c1216d279629299b027d76a4518d9f59f061d0205bf08e8ce53ed99907ee"
      def install
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
