# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScratchmdTest < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc). (TEST RELEASE)"
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.3.5-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.5-test/scratchmd-test_darwin_amd64.tar.gz"
      sha256 "a998d43d26befbae344c9ae8843165a3ea408c1d48368ca68c19971a21af3f54"

      def install
        bin.install "scratchmd-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.5-test/scratchmd-test_darwin_arm64.tar.gz"
      sha256 "1a0819cced52b669e4e504da370f14fe087e44e58c083ff160c58aac25f7ba34"

      def install
        bin.install "scratchmd-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.5-test/scratchmd-test_linux_amd64.tar.gz"
      sha256 "52460fe283d814221cc26392641689aa124390b5ccde3d1a93979e704cca1bdb"
      def install
        bin.install "scratchmd-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.5-test/scratchmd-test_linux_arm64.tar.gz"
      sha256 "1ee5f24b14cb92bdfb49b603b74ffb12a20d5c86ca48cc062d8e07264ac3094a"
      def install
        bin.install "scratchmd-test"
      end
    end
  end

  test do
    system "#{bin}/scratchmd-test --version"
  end
end
