# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScratchmdTest < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc). (TEST RELEASE)"
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.3.22-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.22-test/scratchmd-test_darwin_amd64.tar.gz"
      sha256 "1acf4626c96541dfb4c7bff1624f53449f421f05d3cd6767a79df4a23131094a"

      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.22-test/scratchmd-test_darwin_arm64.tar.gz"
      sha256 "bdc8553977a56779a5af5be9ec895312b210fe946636401d88d79d4174318d17"

      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.22-test/scratchmd-test_linux_amd64.tar.gz"
      sha256 "4cb255f8501f4d0907b3f92e4c4ad203a16389e615d81e48c332e30f4e9634df"
      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.3.22-test/scratchmd-test_linux_arm64.tar.gz"
      sha256 "ad10b34b75bea4acddf6e68675e1b8e6e7fb9de16295a5c438851fceb430c543"
      define_method(:install) do
        bin.install "scratchmd-test"
      end
    end
  end

  test do
    system "#{bin}/scratchmd-test --version"
  end
end
