# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scratchmd < Formula
  desc "Sync local Markdown files with your CMS (Webflow, WordPress, etc). (TEST RELEASE)"
  homepage "https://github.com/whalesync/scratch-cli"
  version "0.2.5-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_darwin_amd64.tar.gz"
      sha256 "5c7845bb8e9e10dc9d52eaea3ccef7e49fc76e4014abc4b37d5eab91bd24b179"

      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_darwin_arm64.tar.gz"
      sha256 "7916091da42f66eba1fe78395763458110e683274abcabbc749fc729f3814f4e"

      def install
        bin.install "scratchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_linux_amd64.tar.gz"
      sha256 "3b17823e326b6fb4cb607974640a9a720d780c0e1081bc307ae2f2be8f695b30"
      def install
        bin.install "scratchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/whalesync/scratch-cli/releases/download/v0.2.5-test/scratchmd-test_linux_arm64.tar.gz"
      sha256 "78a5d6142e5ee1602337b3a2066655dbae439e8c61abda42d8833dcc1985dc87"
      def install
        bin.install "scratchmd"
      end
    end
  end

  test do
    system "#{bin}/scratchmd --version"
  end
end
